Repository prgrms-web-devcourse/Team-Gaerval-Dadok-FE, pull requests merged in 2023-04, with the labels that each got.

#289 [#288] 책장에 있는 책 스타일 수정
  src/ui/InteractiveBook/index.tsx
  src/ui/InteractiveBookShelf/index.tsx
Labels: 🐥 프론트, ♻️ refactor

#292 [#290] 모임 목록 페이지 무한스크롤 구현
  src/apis/group/index.ts
  src/pages/group/index.tsx
  src/queries/group/useEntireGroupsQuery/index.tsx
Labels: 🐥 프론트, ♻️ refactor

#297 [#296] client side인 경우에만 web storage에 접근할 수 있도록 수정
  src/hooks/auth/atoms/index.ts
  src/utils/isClient.ts
  src/utils/storage.tsx
Labels: 🐥 프론트, ✨ feature

#295 [#294] 사용하지 않는 InteractiveBook 관련 컴포넌트 제거
  public/images/book-cover/book1.jpeg
  public/images/book-cover/book2.jpeg
  public/images/book-cover/book3.jpeg
  public/images/book-cover/book4.jpeg
  src/ui/InteractiveBook/InitialBookData.tsx
  src/ui/InteractiveBook/InteractiveBookFront.tsx
  src/ui/InteractiveBook/InteractiveBookSide.tsx
  src/ui/InteractiveBook/InteractiveBookTop.tsx
  src/ui/InteractiveBook/index.tsx
  src/ui/InteractiveBookShelf/InitialBookShelfData.tsx
  src/ui/InteractiveBookShelf/index.tsx
Labels: 🐥 프론트, ✨ feature

#298 [#267] axios interceptor 리팩터링
  src/apis/core/axios.ts
  src/constants/error.ts
  src/hooks/auth/atoms/index.ts
  src/hooks/auth/useAuth.ts
  src/pages/bookarchive/index.tsx
  src/pages/bookshelf/[bookshelfId]/index.tsx
  src/pages/login/redirect/index.tsx
  src/pages/logout/index.tsx
  src/pages/profile/me/add/index.tsx
  src/pages/profile/me/edit/index.tsx
  src/types/error.ts
  src/types/util.ts
  src/ui/BookDetail/BookCommentList.tsx
  src/ui/BookDetail/BookInfo.tsx
  src/ui/BottomNavigation/index.tsx
  src/ui/Group/GroupComment/index.tsx
  src/ui/Group/GroupDetail/GroupInfo.tsx
  src/ui/Group/GroupHeader.tsx
  src/ui/InteractiveBookShelf/index.tsx
  src/ui/common/Layout/index.tsx
  src/utils/helpers/auth.ts
  src/utils/helpers/axiosHandler.ts
  src/utils/helpers/errorCode.ts
  src/utils/helpers/index.ts
  src/utils/storage.tsx
Labels: 🐥 프론트, ♻️ refactor

#302 [#301] package.json script에 hostname 설정
  package.json
Labels: 🐥 프론트, ⚙️ setting

#300 [#291] 책 검색 페이지 무한 스크롤 적용
  src/apis/book/index.ts
  src/queries/book/useBookSearchQuery.ts
  src/types/book.ts
  src/ui/BookSearch/SearchedBook.tsx
  src/ui/BookSearch/index.tsx
Labels: 🐥 프론트, ✨ feature

#304 [#299] 책장 공유 기능 추가
  public/icons/share.svg
  src/pages/bookshelf/[bookshelfId]/index.tsx
  src/ui/common/IconButton/index.tsx
Labels: 🐥 프론트, ✨ feature

#307 [#303] 책 상세 페이지 > 책 상세 내용 더보기 버튼 구현
  src/pages/book/[bookId]/index.tsx
  src/ui/BookDetail/BookInfo.tsx
Labels: 🐥 프론트, ✨ feature

#310 [#293] 모임 생성 인원 사용자 직접입력 기능 구현
  src/constants/groupRadioValues.ts
  src/styles/theme.tsx
  src/ui/BookSearch/SearchedBook.tsx
  src/ui/FormRadio/index.tsx
  src/ui/Group/AddGroupForm.tsx
  src/ui/common/BottomSheet/index.tsx
  src/ui/common/Button/index.tsx
Labels: 🐥 프론트, ♻️ refactor

#316 [#312] 최근 검색어 기능 마크업
  src/hooks/useDebounce.ts
  src/ui/BookSearch/RecentSearches.tsx
  src/ui/BookSearch/index.tsx
Labels: 🐥 프론트, ✨ feature, ♻️ refactor

#318 [#317] 카카오 이미지 CORS 에러를 Next.js rewrites로 처리
  next.config.js
  src/pages/api/book/image.ts
  src/ui/InteractiveBookShelf/index.tsx
  src/utils/helpers/getKakaoBookId.ts
Labels: ♻️ refactor

#320 [#319] 프로필 페이지에 에러 바운더리 적용
  src/hooks/useMounted.ts
  src/pages/profile/[userId]/index.tsx
  src/pages/profile/me/index.tsx
  src/queries/bookshelf/useMySummaryBookshelfQuery/index.ts
  src/queries/bookshelf/useUserSummaryBookshelfQuery/index.ts
  src/queries/group/useMyGroupsQuery/index.ts
  src/queries/user/useMyProfileQuery/index.ts
  src/queries/user/useUserProfileQuery/index.ts
  src/types/query.ts
  src/ui/Profile/MyProfile.tsx
  src/ui/Profile/ProfileBookshelf/MyProfileBookshelfContainer.tsx
  src/ui/Profile/ProfileBookshelf/ProfileBookshelfPresenter.tsx
  src/ui/Profile/ProfileBookshelf/UserProfileBookshelfContainer.tsx
  src/ui/Profile/ProfileBookshelf/index.tsx
  src/ui/Profile/ProfileGroup/ProfileGroupContainer.tsx
  src/ui/Profile/ProfileGroup/ProfileGroupPresenter.tsx
  src/ui/Profile/ProfileGroup/index.tsx
  src/ui/Profile/ProfileInfo/MyProfileInfoContainer.tsx
  src/ui/Profile/ProfileInfo/ProfileInfoPresenter.tsx
  src/ui/Profile/ProfileInfo/UserProfileInfoContainer.tsx
  src/ui/Profile/ProfileInfo/index.tsx
  src/ui/common/QueryErrorBoundaryFallback/index.tsx
Labels: 🐥 프론트, ♻️ refactor

#311 [#285] 책장에 담지 않은 도서에 코멘트를 남길 경우 에러 메세 미노출 이슈 해결
  src/apis/core/axios.ts
  src/pages/book/[bookId]/index.tsx
  src/ui/BookDetail/BookComment.tsx
  src/ui/BookDetail/BookCommentList.tsx
  src/ui/BookDetail/BookInfo.tsx
  src/utils/helpers/error.ts
  src/utils/helpers/errorCode.ts
  src/utils/helpers/index.ts
Labels: 🐥 프론트, 🐛 fix

#324 [#278] Menu 컴포넌트 분리
  src/pages/profile/me/index.tsx
  src/ui/BookDetail/BookComment.tsx
  src/ui/Group/GroupComment/index.tsx
  src/ui/Group/GroupDetail/GroupInfo.tsx
  src/ui/common/Menu/Menu.tsx
  src/ui/common/Menu/MenuItem.tsx
  src/ui/common/Menu/index.ts
Labels: 🐥 프론트, ✨ feature
