Repository prgrms-web-devcourse/Team-Gaerval-Dadok-FE, pull requests merged in 2023-08, with the labels that each got.

#387 [#365] Modal 컴포넌트
  src/hooks/useDisclosure.ts
  src/stories/Base/Modal.stories.tsx
  src/ui/Base/Modal.tsx
Labels: 🐥 프론트, ✨ feature, 🔥 v.1.0

#389 [#388] Input, Select 컴포넌트 에러 처리
  public/icons/warning-circle.svg
  src/stories/Base/Input.stories.tsx
  src/stories/Base/Select.stories.tsx
  src/ui/Base/ErrorMessage.tsx
  src/ui/Base/Input.tsx
  src/ui/Base/Select.tsx
Labels: 🐥 프론트, ✨ feature, 🔥 v.1.0

#392 [#361] BottomNavigation 컴포넌트
  src/stories/Base/BottomNavigation.stories.tsx
  src/ui/Base/BottomNavigation.tsx
  tailwind.config.js
Labels: 🐥 프론트, 🔥 v.1.0

#393 [#362] TopNavigation 컴포넌트 리팩터링
  public/icons/close.svg
  public/icons/hamburger.svg
  src/stories/Base/TopNavigation.stories.tsx
  src/ui/Base/TopNavigation.tsx
Labels: 🐥 프론트, ♻️ refactor, 🔥 v.1.0
