Repository prgrms-web-devcourse/Team-Gaerval-Dadok-FE, pull requests merged in 2023-03, with the labels that each got.

#44 [#38] 모임 생성 페이지 마크업
  public/icons/bookIcon.svg
  src/app/meeting/[id]/page.tsx
  src/app/meeting/create/page.tsx
  src/app/meeting/page.tsx
  src/constants/FormRule/index.ts
  src/ui/CreateMeeting/CreateMeetingForm/index.tsx
  src/ui/CreateMeeting/SelectingBook/SearchingBook/SearchedBook.tsx
  src/ui/CreateMeeting/SelectingBook/SearchingBook/index.tsx
  src/ui/CreateMeeting/SelectingBook/index.tsx
  src/ui/CreateMeeting/index.tsx
  src/ui/GoBack/index.tsx
  src/ui/Meeting/MeetingList/index.tsx
  src/ui/Meeting/MeetingListHeader/index.tsx
  src/ui/Meeting/index.tsx
  src/ui/MeetingDetail/CommentInputBox/index.tsx
  src/ui/MeetingDetail/CommentsList/index.tsx
  src/ui/MeetingDetail/ParticipationBtn/index.tsx
  src/ui/MeetingDetail/ViewMeetingDetail/index.tsx
  src/ui/MeetingDetail/index.tsx
  src/ui/UserForm/UserInput/index.tsx
  src/ui/meeting/MeetingListHeader.tsx
  src/ui/meetingDetail/index.tsx
Labels: 🐥 프론트, ✨ feature

#58 [#57] React Query 초기 세팅
  package.json
  src/app/layout.tsx
  src/components/ReactQueryProvider.tsx
  yarn.lock
Labels: 🐥 프론트, ⚙️ setting

#51 [#37] 책장 컴포넌트 마크업
  src/app/mybookshelf/page.tsx
  src/pages/api/dummyBooks.ts
  src/ui/InteractiveBook/InteractiveBookFront.tsx
  src/ui/InteractiveBook/InteractiveBookSide.tsx
  src/ui/InteractiveBook/InteractiveBookTop.tsx
  src/ui/InteractiveBook/index.tsx
  src/ui/InteractiveBookShelf/index.tsx
  src/ui/MyBookShelfPage/index.tsx
Labels: 🐥 프론트, ✨ feature, ♻️ refactor

#53 [#52] 로그인 페이지 마크업
  public/icons/back.svg
  public/icons/close.svg
  public/icons/goBackIcon.svg
  public/images/kakao.svg
  public/images/logo.svg
  src/app/login/page.tsx
  src/styles/theme.tsx
  src/ui/LoginBottomSheet/index.tsx
  src/ui/common/Button/index.tsx
  src/ui/common/IconButton/index.tsx
  src/ui/common/Logo/index.tsx
Labels: 🐥 프론트, ✨ feature

#54 [#43] 직업 등록 페이지 마크업
  src/app/profile/[id]/add/page.tsx
  src/app/profile/[id]/edit/page.tsx
  src/app/profile/[id]/page.tsx
  src/constants/FormRule/index.ts
  src/ui/AdditionalProfileForm/index.tsx
  src/ui/BottomNavigation/index.tsx
  src/ui/CreateMeeting/CreateMeetingForm/index.tsx
  src/ui/FormInput/index.tsx
  src/ui/FormSelect/index.tsx
  src/ui/ProfileForm/index.tsx
Labels: 🐥 프론트, ✨ feature

#60 [#49] 내 책장 페이지 마크업
  src/app/mybookshelf/page.tsx
  src/ui/MyBookShelfPage/index.tsx
  src/ui/common/TopNavigation/index.tsx
Labels: 🐥 프론트, ✨ feature

#61 [#59] 책 검색 페이지 & 책 상세 페이지 마크업
  src/app/book/[id]/page.tsx
  src/app/book/page.tsx
  src/app/layout.tsx
  src/ui/BottomNavigation/index.tsx
  src/ui/CreateMeeting/SelectingBook/SearchingBook/index.tsx
Labels: 🐥 프론트, ✨ feature

#66 [#62] 다른 사람의 책장 페이지 마크업
  src/app/usersbookshelf/page.tsx
  src/ui/UsersBookShelfPage/UsersBookShelfHeader.tsx
  src/ui/UsersBookShelfPage/UsersBookShelfTag.tsx
  src/ui/UsersBookShelfPage/index.tsx
  src/ui/common/TopNavigation/index.tsx
Labels: 🐥 프론트, ✨ feature

#67 [#65] 북카이브 페이지(메인 페이지) 마크업
  public/icons/search.svg
  src/app/bookarchive/page.tsx
  src/pages/api/dummyBooks.ts
  src/ui/BookList/index.tsx
  src/ui/common/IconButton/index.tsx
Labels: 🐥 프론트, ✨ feature

#72 [#56] 회원가입/로그인 Auth API 연동
  src/api/axios.ts
  src/app/login/page.tsx
  src/app/login/redirect/page.tsx
  src/constants/index.ts
  src/utils/.gitKeep
  src/utils/storage.tsx
Labels: 🐥 프론트, ✨ feature

#63 [#47] 모임 리스트와 모임 상세 페이지 연결 및 UI 일부 변경
  src/app/book/[id]/page.tsx
  src/app/meeting/[id]/page.tsx
  src/app/meeting/create/page.tsx
  src/styles/theme.tsx
  src/ui/CreateMeeting/CreateMeetingForm/index.tsx
  src/ui/CreateMeeting/SelectingBook/SearchingBook/index.tsx
  src/ui/CreateMeeting/SelectingBook/index.tsx
  src/ui/CreateMeeting/index.tsx
  src/ui/GoBack/index.tsx
  src/ui/Meeting/MeetingList/index.tsx
  src/ui/Meeting/index.tsx
  src/ui/MeetingDetail/CommentInputBox/index.tsx
  src/ui/MeetingDetail/CommentsList/index.tsx
  src/ui/MeetingDetail/MeetingInfo/index.tsx
  src/ui/MeetingDetail/ParticipationBtn/index.tsx
  src/ui/MeetingDetail/index.tsx
Labels: 🐥 프론트, ✨ feature, 🐛 fix

#70 프로필 페이지 API 연동
  src/apis/core/axios.ts
  src/apis/users/index.tsx
  src/app/profile/[id]/page.tsx
  src/app/profile/me/add/page.tsx
  src/app/profile/me/edit/page.tsx
  src/app/profile/me/page.tsx
  src/queries/user/useMyProfileQuery/index.ts
  src/queries/user/useUserProfileQuery/index.ts
  src/types/user.ts
  src/ui/ProfileInfo/index.tsx
Labels: 🐥 프론트, ✨ feature

#77 [#76] login 리다이렉션 이슈 해결
  src/app/login/redirect/page.tsx
Labels: 🐥 프론트, 🐛 fix

#81 [#80] mixedContent 이슈 해결을 위한 URL 프록시 적용
  next.config.js
  src/apis/core/axios.ts
Labels: 🐥 프론트, ⚙️ setting

#78 [#71] 프로필용 책장 조회 API 연동
  src/apis/bookshelf/index.ts
  src/app/profile/[id]/page.tsx
  src/app/profile/me/page.tsx
  src/queries/bookshelf/useMySummaryBookshelfQuery/index.ts
  src/queries/bookshelf/useUserSummaryBookshelfQuery/index.ts
  src/types/book.ts
  src/types/bookshelf.ts
  src/types/job.ts
  src/types/user.ts
  src/ui/ProfileInfo/index.tsx
Labels: 🐥 프론트, ✨ feature

#87 [#86] recoil 설치 및 환경 세팅
  package.json
  src/app/layout.tsx
  yarn.lock
Labels: 🐥 프론트, ⚙️ setting

#84 [#69] 책장 페이지에서 책 count에 따른 책장 렌더링
  src/apis/bookshelf/index.ts
  src/app/bookarchive/page.tsx
  src/app/mybookshelf/page.tsx
  src/app/usersbookshelf/page.tsx
  src/pages/api/dummyBooks.ts
  src/types/.gitKeep
  src/types/book.ts
  src/types/bookshelf.ts
  src/ui/InteractiveBook/InteractiveBookFront.tsx
  src/ui/InteractiveBook/InteractiveBookSide.tsx
  src/ui/InteractiveBook/index.tsx
  src/ui/InteractiveBookShelf/index.tsx
  src/ui/ProfileInfo/index.tsx
Labels: 🐥 프론트, ✨ feature, 🐛 fix

#82 [#74] 모임 리스트 페이지 검색창 구현
  src/ui/Meeting/MeetingSearch/index.tsx
  src/ui/Meeting/index.tsx
  src/ui/MeetingDetail/index.tsx
Labels: 🐥 프론트, ✨ feature

#89 [#79] useAuth 훅, AuthRequired 구현
  src/app/login/redirect/page.tsx
  src/hooks/auth/atoms/index.ts
  src/hooks/auth/index.ts
  src/hooks/auth/useAuth.ts
  src/ui/AuthRequired/index.tsx
Labels: 🐥 프론트, ✨ feature

#88 [#73] 프로필 추가정보 입력 페이지 API 연동
  src/apis/job/index.ts
  src/app/profile/me/add/page.tsx
  src/app/profile/me/page.tsx
  src/constants/FormRule/index.ts
  src/queries/job/useAllJobQuery/index.ts
  src/types/job.ts
  src/types/user.ts
  src/ui/AdditionalProfileForm/index.tsx
  src/ui/CreateMeeting/CreateMeetingForm/index.tsx
  src/ui/FormInput/index.tsx
  src/ui/ProfileInfo/index.tsx
Labels: 🐥 프론트, ✨ feature

#97 [#94] 로그인하지 않은 사용자 프로필 페이지 접근 못하도록 수정
  src/app/profile/me/layout.tsx
  src/app/profile/me/page.tsx
  src/ui/BottomNavigation/NavigationItem/index.tsx
  src/ui/BottomNavigation/index.tsx
  src/ui/LoginBottomSheet/index.tsx
Labels: 🐥 프론트, ✨ feature

#100 [#99] 추가정보 입력 페이지로 이동하지 않는 이슈
  src/app/profile/me/add/page.tsx
  src/app/profile/me/page.tsx
  src/ui/AdditionalProfileForm/index.tsx
Labels: 🐥 프론트, 🐛 fix

#91 [#85] 책장 페이지에 책 목록 API 연결
  src/apis/bookshelf/index.ts
  src/app/bookarchive/page.tsx
  src/app/mybookshelf/page.tsx
  src/app/usersbookshelf/page.tsx
  src/pages/api/dummyBooks.ts
  src/queries/bookshelf/useBookshelfBookListQuery/index.ts
  src/queries/bookshelf/useBookshelfInfoQuery/index.ts
  src/ui/InteractiveBookShelf/index.tsx
  src/ui/ProfileInfo/index.tsx
Labels: 🐥 프론트, ✨ feature, ♻️ refactor

#104 [#90] login 후 추가 정보 입력 페이지로 이동
  src/app/login/redirect/page.tsx
Labels: 🐥 프론트, ✨ feature

#95 [#83] 모임 상세 페이지 참여버튼, 글 작성, 글 수정, 글 삭제
  src/ui/MeetingDetail/CommentDeleteModal/index.tsx
  src/ui/MeetingDetail/CommentInputBox/index.tsx
  src/ui/MeetingDetail/CommentModifyModal/index.tsx
  src/ui/MeetingDetail/CommentsList/index.tsx
  src/ui/MeetingDetail/MeetingInfo/index.tsx
  src/ui/MeetingDetail/ParticipationBtn/index.tsx
  src/ui/MeetingDetail/index.tsx
Labels: 🐥 프론트, ✨ feature, 🐛 fix

#109 [#98] 프로필 수정 API 연동
  src/app/profile/me/add/page.tsx
  src/app/profile/me/edit/page.tsx
  src/ui/AdditionalProfileForm/index.tsx
Labels: 🐥 프론트, ✨ feature

#112 [#108] 책 검색 컴포넌트 API 연동 및 리팩터링
  public/icons/logo_sm.svg
  src/apis/book/index.ts
  src/app/book/page.tsx
  src/ui/BookSearch/index.tsx
  src/ui/CreateMeeting/SelectingBook/SearchingBook/SearchedBook.tsx
  src/ui/CreateMeeting/SelectingBook/SearchingBook/index.tsx
  src/ui/CreateMeeting/SelectingBook/index.tsx
  src/ui/CreateMeeting/index.tsx
  src/utils/debounce.ts
Labels: 🐥 프론트, ♻️ refactor

#115 [#105] 책 상세 페이지 > 북마크 마크업, 책 정보 컴포넌트로 분리
  .eslintrc.json
  next.config.js
  public/icons/bookmark.svg
  src/app/book/[id]/page.tsx
  src/types/book.ts
  src/ui/BookDetail/BookInfo/index.tsx
  src/ui/common/IconButton/index.tsx
Labels: 🐥 프론트, ✨ feature

#116 [#114] axios header accessToken이 null인 경우 예외처리
  src/apis/core/axios.ts
Labels: 🐥 프론트, 🐛 fix

#117 [#110] 모임 전체 목록 API 연동
  src/apis/Meeting/index.ts
  src/queries/meeting/useEntireMeetingListQuery/index.tsx
  src/types/meeting.ts
  src/ui/Meeting/MeetingList/index.tsx
  src/ui/Meeting/index.tsx
Labels: 🐥 프론트, ✨ feature

#121 [#108] 모임 생성 페이지에서도 책 검색 컴포넌트 사용 가능하도록 수정
  src/ui/BookSearch/index.tsx
  src/ui/CreateMeeting/CreateMeetingForm/index.tsx
Labels: 🐥 프론트, ♻️ refactor

#124 [#123] bottom sheet가 매끄럽지 않게 닫히지 않는 이슈
  src/ui/common/BottomSheet/index.tsx
Labels: 🐥 프론트, 🐛 fix

#111 [#92] 다른 사용자 책장 페이지 > api 연결 및 다이나믹 라우팅 적용
  src/apis/bookshelf/index.ts
  src/app/bookshelf/[bookshelfId]/page.tsx
  src/app/mybookshelf/page.tsx
  src/app/usersbookshelf/page.tsx
  src/queries/bookshelf/useBookshelfBookListQuery/index.ts
  src/queries/bookshelf/useBookshelfInfoQuery/index.ts
  src/types/bookshelf.ts
  src/ui/MyBookShelfPage/index.tsx
  src/ui/UserJobInfoTag/index.tsx
  src/ui/UsersBookShelfPage/UsersBookShelfHeader.tsx
  src/ui/UsersBookShelfPage/index.tsx
Labels: 🐥 프론트, ✨ feature, ♻️ refactor

#127 [#120] 모임 상세 페이지 모임정보 API 연결
  src/apis/Meeting/index.ts
  src/app/meeting/[id]/page.tsx
  src/queries/meeting/useMeetingDetailInfoQuery/index.tsx
  src/types/meetingDetail.ts
  src/ui/MeetingDetail/MeetingInfo/index.tsx
  src/ui/MeetingDetail/index.tsx
Labels: 🐥 프론트, ✨ feature

#130 [#125] 책 생성 API 연동 & 모임 생성 API 연동
  src/apis/Meeting/index.ts
  src/apis/book/index.ts
  src/constants/FormRule/index.ts
  src/types/meeting.ts
  src/ui/BookSearch/index.tsx
  src/ui/CreateMeeting/CreateMeetingForm/index.tsx
Labels: 🐥 프론트, ✨ feature

#133 [#129] 책 상세 페이지 > 책 상세 조회 api 연결
  src/apis/book/index.ts
  src/app/book/[id]/page.tsx
  src/queries/book/useBookInfoQuery.ts
  src/ui/BookDetail/BookInfo.tsx
Labels: 🐥 프론트, ✨ feature

#132 [#128] 모임 상세 페이지 댓글 리스트 API 연동
  src/apis/Meeting/index.ts
  src/queries/meeting/useMeetingCommentsQuery/index.tsx
  src/queries/meeting/useMeetingInfoQuery/index.tsx
  src/types/meetingDetailCommentsList.ts
  src/ui/MeetingDetail/CommentsList/index.tsx
  src/ui/MeetingDetail/index.tsx
Labels: 🐥 프론트, ✨ feature

#119 [#118] 전역 패딩 설정
  src/app/book/[id]/page.tsx
  src/app/book/page.tsx
  src/app/bookarchive/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/meeting/page.tsx
  src/app/profile/me/page.tsx
  src/ui/BookSearch/index.tsx
  src/ui/BottomNavigation/index.tsx
  src/ui/CreateMeeting/CreateMeetingForm/index.tsx
  src/ui/Meeting/MeetingListHeader/index.tsx
  src/ui/Meeting/index.tsx
  src/ui/ProfileForm/index.tsx
  src/ui/ProfileInfo/index.tsx
  src/ui/common/Layout/index.tsx
Labels: 🐥 프론트, 🐛 fix

#136 [#135] 모임 참여 API 연동
  src/apis/Meeting/index.ts
  src/ui/MeetingDetail/index.tsx
Labels: 🐥 프론트, ✨ feature

#141 [#75] 페이지 전환 애니메이션 적용
  src/app/book/page.tsx
  src/app/bookarchive/page.tsx
  src/app/meeting/page.tsx
  src/app/profile/me/add/page.tsx
  src/app/profile/me/edit/page.tsx
  src/app/profile/me/page.tsx
  src/ui/BookSearch/index.tsx
  src/ui/BottomNavigation/index.tsx
  src/ui/FormInput/index.tsx
  src/ui/FormSelect/index.tsx
  src/ui/Meeting/MeetingSearch/index.tsx
  src/ui/Meeting/index.tsx
  src/ui/ProfileInfo/index.tsx
  src/ui/common/Layout/index.tsx
Labels: 🐥 프론트, ✨ feature

#140 [#138] 모임 상세 페이지 댓글 생성 API 연동
  src/apis/Meeting/index.ts
  src/types/meetingDetailCommentsList.ts
  src/ui/MeetingDetail/CommentInputBox/index.tsx
  src/ui/MeetingDetail/CommentsList/index.tsx
  src/ui/MeetingDetail/index.tsx
Labels: 🐥 프론트, ✨ feature

#148 [#139] 책 상세 페이지 > 코멘트 목록 마크업 수정
  src/app/book/[id]/page.tsx
  src/styles/theme.tsx
  src/ui/BookDetail/BookComment.tsx
  src/ui/BookDetail/BookCommentList.tsx
  src/ui/BookDetail/type.ts
Labels: 🐥 프론트, ✨ feature

#146 [#142] 모임 상세 페이지 모임장 모임 수정 및 삭제 버튼
  src/ui/MeetingDetail/MeetingInfo/index.tsx
  src/ui/MeetingDetail/index.tsx
Labels: 🐥 프론트, ✨ feature

#145 [#143] 책장 페이지 > 책 클릭시 책장 상세 페이지로 이동
  src/ui/InteractiveBook/index.tsx
  src/ui/InteractiveBookShelf/index.tsx
Labels: 🐥 프론트, ✨ feature

#153 [#147] 모임 삭제 API 연동, 모임 상세 페이지 댓글이 없는 경우 안내 텍스트 추가
  src/apis/Meeting/index.ts
  src/apis/core/axios.ts
  src/ui/MeetingDetail/CommentsList/index.tsx
  src/ui/MeetingDetail/index.tsx
Labels: 🐥 프론트, ✨ feature, 🐛 fix

#150 [#131] 모임 수정 페이지 API 연동
  src/apis/Meeting/index.ts
  src/app/meeting/[id]/edit/page.tsx
  src/app/meeting/create/page.tsx
  src/constants/FormRule/index.ts
  src/styles/theme.tsx
  src/ui/CreateMeeting/index.tsx
  src/ui/FormInput/index.tsx
  src/ui/MeetingDetail/MeetingInfo/index.tsx
  src/ui/MeetingDetail/index.tsx
  src/ui/MeetingForm/AddMettingForm.tsx
  src/ui/MeetingForm/EditMettingForm.tsx
  src/ui/MeetingForm/index.tsx
Labels: 🐥 프론트, ✨ feature

#155 [#144] 책등 이미지 api routes를 활용하여 에러 해결
  package.json
  src/apis/bookshelf/index.ts
  src/hooks/useScroll.ts
  src/pages/api/getBookColor.ts
  src/ui/InteractiveBook/index.tsx
  yarn.lock
Labels: 🐥 프론트, 🐛 fix, ⚙️ setting

#158 [#137] 프로필 페이지에서 모임 목록 보여주기
  src/apis/Meeting/index.ts
  src/app/profile/[id]/page.tsx
  src/app/profile/me/page.tsx
  src/queries/meeting/useMyMeetingListQuery/index.ts
  src/ui/Meeting/MeetingList/MeetingListItem.tsx
  src/ui/Meeting/MeetingList/index.tsx
  src/ui/ProfileBookshelf/index.tsx
  src/ui/ProfileInfo/index.tsx
Labels: 🐥 프론트, ✨ feature

#164 [#160] 토스트 컴포넌트 작성
  src/hooks/toast/atoms/index.ts
  src/hooks/toast/index.ts
  src/hooks/toast/useToast.ts
  src/ui/AdditionalProfileForm/index.tsx
  src/ui/common/Layout/index.tsx
  src/ui/common/Toast/ToastItem.tsx
  src/ui/common/Toast/index.tsx
Labels: 🐥 프론트, ✨ feature

#161 [#157] Safari에서 BottomNav와 겹쳐 보이는 버그 수정
  src/ui/InteractiveBook/index.tsx
Labels: 🐥 프론트, 🐛 fix

#163 [#159] 메인 페이지 > 기존 마크업 다듬기 및 더미 데이터 제거
  src/app/bookarchive/page.tsx
  src/pages/api/dummyBooks.ts
  src/ui/BookList/index.tsx
  src/ui/InteractiveBook/index.tsx
  src/ui/Recommended/RecommendedBooks.tsx
  src/ui/Recommended/RecommendedBookshelf.tsx
  src/ui/Recommended/index.tsx
Labels: 🐥 프론트, ✨ feature, ♻️ refactor

#162 [#106] 책 상세 페이지 > 코멘트 작성 모달 마크업
  public/icons/close.svg
  src/ui/BookDetail/BookCommentList.tsx
  src/ui/BookDetail/CreateCommentDrawer.tsx
Labels: 🐥 프론트, ✨ feature

#171 [#169] 책 코멘트 > 코멘트 생성 api 연결
  src/apis/book/index.ts
  src/types/book.ts
  src/ui/BookDetail/BookCommentList.tsx
  src/ui/BookDetail/CreateCommentDrawer.tsx
Labels: 🐥 프론트, ✨ feature

#172 [#156] 모임 가입 폼 추가
  src/apis/core/axios.ts
  src/constants/FormRule/index.ts
  src/types/meeting.ts
  src/ui/FormInput/index.tsx
  src/ui/FormRadio/index.tsx
  src/ui/MeetingDetail/index.tsx
  src/ui/MeetingForm/AddMettingForm.tsx
  src/ui/MeetingForm/radioValues.tsx
Labels: 🐥 프론트, ✨ feature

#176 [#170] 책 코멘트 > 코멘트 목록 조회 api 연결
  src/apis/book/index.ts
  src/queries/book/useBookCommentsQuery.ts
  src/types/book.ts
  src/ui/BookDetail/BookComment.tsx
  src/ui/BookDetail/BookCommentList.tsx
Labels: 🐥 프론트, ✨ feature

#174 [#173] 모임 상세 페이지 댓글 삭제 API 연동
  src/apis/Meeting/index.ts
  src/apis/core/axios.ts
  src/ui/MeetingDetail/CommentDeleteModal/index.tsx
  src/ui/MeetingDetail/CommentModifyModal/index.tsx
  src/ui/MeetingDetail/CommentsList/index.tsx
  src/ui/MeetingDetail/index.tsx
Labels: 🐥 프론트, ✨ feature

#183 [#181] 모임 생성, 수정시 시작일로 오늘 날짜가 선택되지 않는 이슈
  src/constants/FormRule/index.ts
  src/ui/MeetingForm/AddMettingForm.tsx
Labels: 🐥 프론트, 🐛 fix

#177 [#165] 책 컴포넌트 > 책등 색깔 요청시간 개선
  src/app/bookshelf/[bookshelfId]/page.tsx
  src/pages/api/book/image.ts
  src/pages/api/getBookColor.ts
  src/pages/api/hello.ts
  src/ui/InteractiveBook/InteractiveBookFront.tsx
  src/ui/InteractiveBook/InteractiveBookSide.tsx
  src/ui/InteractiveBook/InteractiveBookTop.tsx
  src/ui/InteractiveBook/index.tsx
  src/ui/InteractiveBookShelf/index.tsx
  src/ui/common/TopNavigation/index.tsx
Labels: 🐥 프론트, ✨ feature

#186 [#107] 책 상세 페이지 > 코멘트 삭제 모달 마크업
  src/styles/theme.tsx
  src/ui/BookDetail/BookComment.tsx
  src/ui/BookDetail/BookCommentList.tsx
  src/ui/common/Button/index.tsx
Labels: 🐥 프론트, ✨ feature

#178 [#166] 메인 페이지 > 비로그인 사용자 책장 추천 api 연결
  src/apis/recommend/index.ts
  src/app/bookarchive/page.tsx
  src/queries/recommend/useUnAuthRecommendedBookshelfQuery/index.tsx
  src/types/bookshelf.ts
  src/ui/BookArchive/BookArchiveForUnAuth.tsx
  src/ui/BookArchive/index.tsx
  src/ui/InteractiveBookShelf/index.tsx
  src/ui/Recommended/RecommendedBooks.tsx
Labels: 🐥 프론트, ✨ feature

#191 [#187] 모임 목록 페이지 UI 변경
  public/icons/lock.svg
  public/icons/unlock.svg
  src/types/meeting.ts
  src/ui/Meeting/MeetingList/MeetingListItem.tsx
Labels: 🐥 프론트, 🐛 fix

#190 [#180] 모임 상세 페이지 모임 참여 비밀번호 입력 폼 구현
  src/apis/Meeting/index.ts
  src/types/meetingDetail.ts
  src/ui/MeetingDetail/CommentsList/index.tsx
  src/ui/MeetingDetail/MeetingInfo/index.tsx
  src/ui/MeetingDetail/index.tsx
  src/ui/MeetingForm/AddMeetingForm.tsx
  src/ui/MeetingForm/EditMeetingForm.tsx
  src/ui/MeetingForm/index.tsx
Labels: 🐥 프론트, ✨ feature

#189 [#175] 모임 상세 페이지 댓글 수정 API 연결
  src/apis/Meeting/index.ts
  src/ui/MeetingDetail/CommentModifyModal/index.tsx
  src/ui/MeetingDetail/CommentsList/index.tsx
  src/ui/MeetingDetail/index.tsx
Labels: 🐥 프론트, ✨ feature

#196 [#185] 책 상세 페이지 > 코멘트 수정 기능 구현
  src/apis/book/index.ts
  src/queries/book/useBookCommentPatchMutation.ts
  src/types/book.ts
  src/ui/BookDetail/BookComment.tsx
  src/ui/BookDetail/BookCommentList.tsx
  src/ui/BookDetail/CommentDrawer.tsx
  src/ui/BookDetail/CreateCommentDrawer.tsx
  src/ui/BookDetail/type.ts
Labels: 🐥 프론트, ✨ feature

#197 [#182] 메인 페이지 > 로그인한 사용자 책장 추천 api 연결
  src/apis/recommend/index.ts
  src/app/bookarchive/page.tsx
  src/queries/recommend/useAuthRecommendedBooks/index.tsx
  src/queries/recommend/useAuthRecommendedBookshelf/index.tsx
  src/queries/user/useMyProfileQuery/index.ts
  src/types/bookshelf.ts
  src/ui/BookArchive/BookArchiveForAuth.tsx
Labels: 🐥 프론트, ✨ feature

#192 [#184] 에러 바운더리 설정
  package.json
  src/app/_error.tsx
  src/app/layout.tsx
  yarn.lock
Labels: 🐥 프론트, ✨ feature

#194 [#193] 내 프로필 페이지 스켈레톤 적용
  src/app/bookarchive/page.tsx
  src/app/profile/me/page.tsx
  src/queries/bookshelf/useMySummaryBookshelfQuery/index.ts
  src/queries/meeting/useMyMeetingListQuery/index.ts
  src/queries/user/useMyProfileQuery/index.ts
  src/ui/ProfileBookshelf/index.tsx
  src/ui/ProfileInfo/index.tsx
Labels: 🐥 프론트, ♻️ refactor

#204 [#198] 프로필 페이지 > 유저 책장 페이지 라우팅주소 수정
  src/ui/ProfileBookshelf/index.tsx
Labels: 🐥 프론트, 🐛 fix

#203 [#199] 책 상세 페이지 > 코멘트 삭제 기능 구현
  src/apis/book/index.ts
  src/ui/BookDetail/BookComment.tsx
  src/ui/BookDetail/BookCommentList.tsx
Labels: 🐥 프론트, ✨ feature

#208 [#206] 책장 이름에 유저 이름 or 닉네임 중 한가지로 통일
  src/app/bookarchive/page.tsx
  src/app/bookshelf/[bookshelfId]/page.tsx
  src/ui/BookArchive/index.tsx
Labels: 🐥 프론트, 🐛 fix

#209 [#151] 책 상세 페이지 > 책장에 책 꽂기 api 연결
  src/apis/book/index.ts
  src/queries/book/useBookUserInfoQuery.ts
  src/types/book.ts
  src/ui/BookDetail/BookInfo.tsx
Labels: 🐥 프론트, ✨ feature

#207 [#179] Top Navigation UI 통일, 뒤로가기 기능 구현
  src/app/book/[id]/page.tsx
  src/app/meeting/[id]/edit/page.tsx
  src/app/meeting/[id]/page.tsx
  src/app/meeting/create/page.tsx
  src/app/profile/me/edit/page.tsx
  src/ui/common/TopNavigation/index.tsx
Labels: 🐥 프론트, ✨ feature, 🐛 fix

#214 [#213] 책 코멘트 수정, 삭제 시 404 에러 해결
  src/apis/book/index.ts
  src/apis/meeting/index.ts
  src/apis/recommend/index.ts
  src/pages/_app.tsx
Labels: 🐥 프론트, 🐛 fix

#217 [#215] 내 프로필 페이지 스켈레톤 적용
  src/components/ReactQueryProvider.tsx
  src/pages/_app.tsx
  src/pages/profile/[userId]/index.tsx
  src/pages/profile/me/add/index.tsx
  src/pages/profile/me/edit/index.tsx
  src/pages/profile/me/index.tsx
  src/queries/bookshelf/useMySummaryBookshelfQuery/index.ts
  src/queries/meeting/useMyMeetingListQuery/index.ts
  src/queries/user/useMyProfileQuery/index.ts
  src/ui/Profile/MyProfile.tsx
  src/ui/Profile/ProfileBookshelf.tsx
  src/ui/Profile/ProfileForm.tsx
  src/ui/Profile/ProfileInfo.tsx
  src/ui/Profile/ProfileMeeting.tsx
  src/ui/ProfileForm/index.tsx
Labels: 🐥 프론트, ✨ feature

#216 [#205] 책 상세 페이지 > 책장에 책 꽂은 사용자 보여주는 api 연결
  src/apis/recommend/index.ts
  src/queries/book/useBookUserInfoQuery.ts
  src/ui/BookDetail/BookInfo.tsx
Labels: 🐥 프론트, ✨ feature

#218 [#212] 조건에 따른 댓글 노출 제한과 안내 텍스트 작성, 모임 참여버튼 클릭시 조건에 따른 바텀시트 노출
  src/apis/meeting/index.ts
  src/constants/initialBookGroupComments.ts
  src/ui/Meeting/MeetingList/MeetingListItem.tsx
  src/ui/Meeting/index.tsx
  src/ui/MeetingDetail/CommentInputBox/index.tsx
  src/ui/MeetingDetail/CommentsList/GuideMessage.tsx
  src/ui/MeetingDetail/CommentsList/index.tsx
  src/ui/MeetingDetail/MeetingInfo/index.tsx
  src/ui/MeetingDetail/index.tsx
Labels: 🐥 프론트, ✨ feature, ♻️ refactor

#221 [#220] Next.js rewrites config 제거
  next.config.js
  src/apis/book/index.ts
  src/apis/bookshelf/index.ts
  src/apis/core/axios.ts
  src/apis/job/index.ts
  src/apis/meeting/index.ts
  src/apis/recommend/index.ts
  src/apis/users/index.tsx
Labels: 🐥 프론트, ♻️ refactor

#223 [#222] 다른 사용자 프로필 페이지 스켈레톤 작성
  src/pages/profile/[userId]/index.tsx
  src/ui/common/TopNavigation/index.tsx
Labels: 🐥 프론트, ✨ feature

#231 [#228] 토스트 가운데 정렬
  src/ui/common/Toast/ToastItem.tsx
  src/ui/common/Toast/index.tsx
Labels: 🐥 프론트, 🐛 fix

#230 [#229] 닉네임 정규식 수정
  src/constants/FormRule/index.ts
Labels: 🐥 프론트, 🐛 fix

#238 [#227] 모임 상세 페이지 댓글 삭제 모달 UI변경, 모임장 모임 수정 삭제 버튼 위치 변경
  src/pages/meeting/[meetingId]/index.tsx
  src/ui/Meeting/MeetingList/MeetingListItem.tsx
  src/ui/MeetingDetail/MeetingInfo/index.tsx
  src/ui/MeetingDetail/index.tsx
Labels: 🐥 프론트, ✨ feature, ♻️ refactor

#232 [#103] 책장 페이지 > 무한 스크롤 기능 추가
  package.json
  src/apis/bookshelf/index.ts
  src/pages/bookshelf/[bookshelfId]/index.tsx
  src/queries/bookshelf/useBookshelfBookListQuery/index.ts
  yarn.lock
Labels: 🐥 프론트, ✨ feature, ⚙️ setting

#240 [#239] 모임 상세 페이지 댓글 삭제 UI 변경
  src/ui/Meeting/index.tsx
  src/ui/MeetingDetail/CommentDeleteModal/index.tsx
  src/ui/MeetingDetail/CommentModifyModal/index.tsx
  src/ui/MeetingDetail/index.tsx
Labels: 🐥 프론트, ♻️ refactor

#242 [#241] 글로벌 폰트 적용안되던 Chakra Heading 컴포넌트 제거
  src/pages/404.tsx
  src/pages/_app.tsx
  src/pages/book/[bookId]/index.tsx
  src/pages/error.tsx
  src/pages/login/index.tsx
  src/pages/profile/me/add/index.tsx
  src/styles/theme.tsx
  src/ui/LoginBottomSheet/index.tsx
Labels: 🐥 프론트, 🐛 fix

#243 [#188] 토큰이 만료되어 UnAuthorized 에러가 발생하는 경우 login 페이지로 이동
  next.config.js
  src/apis/book/index.ts
  src/apis/bookshelf/index.ts
  src/apis/core/axios.ts
  src/apis/job/index.ts
  src/apis/meeting/index.ts
  src/apis/recommend/index.ts
  src/apis/users/index.tsx
  src/constants/error.ts
  src/constants/index.ts
  src/constants/storage.ts
  src/hooks/auth/useAuth.ts
Labels: 🐥 프론트, ✨ feature

#245 [#244] 서비스의 디자인 요소들 통일
  src/ui/BookSearch/index.tsx
  src/ui/BottomNavigation/index.tsx
  src/ui/LoginBottomSheet/index.tsx
  src/ui/Meeting/MeetingListHeader/index.tsx
  src/ui/MeetingForm/AddMeetingForm.tsx
  src/ui/Profile/MyProfile.tsx
Labels: 🐥 프론트, ♻️ refactor

#246 [#235] 메인 페이지 > 디자인 보수 작업
  public/icons/job-card.svg
  public/icons/more-circle.svg
  src/pages/bookarchive/index.tsx
  src/ui/BookArchive/BookArchiveForAuth.tsx
  src/ui/InteractiveBookShelf/index.tsx
  src/ui/Profile/ProfileBookshelf.tsx
  src/ui/Profile/ProfileInfo.tsx
  src/ui/Profile/ProfileMeeting.tsx
  src/ui/Recommended/RecommendedBooks.tsx
  src/ui/Recommended/RecommendedBookshelf.tsx
  src/ui/common/IconButton/index.tsx
Labels: 🐥 프론트, ♻️ refactor

#247 [hofix] page header 수정
  src/ui/BookSearch/index.tsx
  src/ui/InteractiveBookShelf/index.tsx
  src/ui/Meeting/MeetingListHeader/index.tsx
  src/ui/Meeting/index.tsx
Labels: 🐥 프론트, ♻️ refactor

#249 [#248] 레이아웃 스크롤 중첩
  src/ui/BottomNavigation/NavigationItem/index.tsx
  src/ui/BottomNavigation/index.tsx
  src/ui/common/Layout/index.tsx
Labels: 🐥 프론트, 🐛 fix

#251 [#248] 스크롤 중첩 이슈
  src/ui/BottomNavigation/NavigationItem/index.tsx
  src/ui/BottomNavigation/index.tsx
  src/ui/common/Layout/index.tsx
Labels: 🐥 프론트, 🐛 fix

#252 [hotfix] 바텀 네비게이션 경로 수정
  src/ui/common/Layout/index.tsx
Labels: 🐥 프론트, 🐛 fix

#253 [hotfix] top 네비게이션 디자인 수정
  public/icons/back.svg
  public/icons/plus-circle.svg
  src/queries/book/useBookUserInfoQuery.ts
  src/ui/BookDetail/BookCommentList.tsx
  src/ui/BookDetail/BookInfo.tsx
  src/ui/Meeting/MeetingListHeader/index.tsx
  src/ui/common/IconButton/index.tsx
  src/ui/common/TopNavigation/index.tsx
Labels: 🐥 프론트, ♻️ refactor

#255 [Hotfix] 책검색api cursorId 파라미터 수정
  next.config.js
  src/apis/bookshelf/index.ts
  src/pages/bookarchive/index.tsx
  src/pages/bookshelf/[bookshelfId]/index.tsx
  src/queries/bookshelf/useBookshelfBookListQuery/index.ts
  src/types/book.ts
  src/ui/BookArchive/BookArchiveForAuth.tsx
  src/ui/BookArchive/BookArchiveForUnAuth.tsx
  src/ui/InteractiveBook/InitialBookData.tsx
  src/ui/InteractiveBookShelf/InitialBookShelfData.tsx
  src/ui/InteractiveBookShelf/index.tsx
Labels: 🐥 프론트, 🐛 fix

#256 Update README.md
  README.md
Labels: 🐥 프론트, 📝 docs

#264 [#263] MeetingDetail -> GroupDetail 컴포넌트 이름 변경
  src/pages/group/[groupId]/index.tsx
  src/ui/Group/GroupComment/CommentDeleteModal.tsx
  src/ui/Group/GroupComment/CommentInputBox.tsx
  src/ui/Group/GroupComment/CommentModifyModal.tsx
  src/ui/Group/GroupComment/GuideMessage.tsx
  src/ui/Group/GroupComment/index.tsx
  src/ui/Group/GroupDetail/GroupInfo.tsx
  src/ui/Group/GroupDetail/index.tsx
  src/ui/Group/GroupSearch.tsx
  src/ui/Profile/MyProfile.tsx
  src/ui/Profile/ProfileGroup.tsx
Labels: 🐥 프론트, ♻️ refactor

#273 [#270] 상단 네비게이션 > cursor pointer 옵션 삽입
  src/ui/common/TopNavigation/index.tsx
Labels: 🐥 프론트, ✨ feature

#275 [#271] Book Type 정리
  src/apis/book/index.ts
  src/pages/book/[bookId]/index.tsx
  src/queries/book/useBookCommentsQuery.ts
  src/queries/book/useBookInfoQuery.ts
  src/types/book.ts
  src/types/bookshelf.ts
  src/types/group.ts
  src/ui/BookDetail/BookInfo.tsx
  src/ui/BookSearch/index.tsx
  src/ui/InteractiveBookShelf/index.tsx
  src/ui/Recommended/RecommendedBooks.tsx
Labels: 🐥 프론트, ♻️ refactor

#277 [#276] 모임 상세 페이지 댓글 수정 삭제 UI 통일
  src/ui/Group/GroupComment/CommentDeleteModal.tsx
  src/ui/Group/GroupComment/CommentModifyModal.tsx
  src/ui/Group/GroupComment/index.tsx
Labels: 🐥 프론트, ♻️ refactor

#284 [#272] Bookshelf Type 정리
  src/apis/bookshelf/index.ts
  src/apis/recommend/index.ts
  src/pages/bookshelf/[bookshelfId]/index.tsx
  src/queries/bookshelf/useBookshelfBookListQuery/index.ts
  src/queries/recommend/useAuthRecommendedBooks/index.tsx
  src/queries/recommend/useAuthRecommendedBookshelf/index.tsx
  src/types/bookshelf.ts
  src/ui/InteractiveBookShelf/index.tsx
  src/ui/Profile/ProfileBookshelf.tsx
  src/ui/Recommended/RecommendedBookshelf.tsx
Labels: 🐥 프론트, ♻️ refactor
