Repository prgrms-web-devcourse/Team-Gaerval-Dadok-FE, pull requests merged in 2023-06, with the labels that each got.

#346 [#305] 책 표지를 Next/Image로 교체
  next.config.js
  package.json
  src/types/colorthief.d.ts
  src/ui/InteractiveBook/index.tsx
  src/ui/InteractiveBookShelf/index.tsx
  src/utils/helpers/getKakaoBookId.ts
  yarn.lock
Labels: 🐥 프론트, ♻️ refactor

#348 [#347] 로그인하지 않은 사용자가 책 상세 페이지에서 내용을 보지 못하는 문제 해결
  src/pages/book/[bookId]/index.tsx
  src/ui/BookDetail/BookInfo.tsx
Labels: 🐥 프론트, 🐛 fix

#336 [#306] 유저 책장 좋아요 기능 구현
  public/icons/like.svg
  src/apis/bookshelf/index.ts
  src/pages/bookshelf/[bookshelfId]/index.tsx
  src/queries/bookshelf/useBookshelfLikeMutation.ts
  src/types/bookshelf.ts
  src/ui/BookArchive/BookArchiveForAuth.tsx
  src/ui/BookArchive/BookArchiveForUnAuth.tsx
  src/ui/Profile/ProfileBookshelf/ProfileBookshelfPresenter.tsx
  src/ui/Recommended/RecommendedBookshelf.tsx
  src/ui/common/BookshelfLike/LikeButton.tsx
  src/ui/common/BookshelfLike/LikeCount.tsx
  src/ui/common/BookshelfLike/index.tsx
  src/ui/common/LikeButton/index.tsx
Labels: 🐥 프론트, ✨ feature
