Repository prgrms-web-devcourse/Team-Gaerval-Dadok-FE, pull requests merged in 2023-10, with the labels that each got.

#417 [#413] Issue 템플릿에 v1.0 라벨 추가
  .github/ISSUE_TEMPLATE/issue-template.md
Labels: 🐥 프론트, ⚙️ setting, 🔥 v.1.0

#400 [#398] RadioButton 컴포넌트
  src/stories/Base/RadioButton.stories.tsx
  src/ui/Base/RadioButton.tsx
Labels: 🐥 프론트, 🔥 v.1.0

#421 [#405] [레이아웃] 공통 레이아웃
  .storybook/preview.ts
  src/stories/Base/BottomNavigation.stories.tsx
  src/stories/Base/TopHeader.stories.tsx
  src/stories/layout/Layout.stories.tsx
  src/ui/Base/BottomNavigation.tsx
  src/ui/Base/TopHeader.tsx
  src/v1/layout/index.tsx
  tailwind.config.js
Labels: 🐥 프론트, ✨ feature, 🔥 v.1.0
