Repository prgrms-web-devcourse/Team-Gaerval-Dadok-FE, pull requests merged in 2023-05, with the labels that each got.

#329 [#325] logout api 연결
  src/apis/users/index.tsx
  src/pages/logout/index.tsx
  src/pages/profile/me/index.tsx
Labels: 🐥 프론트, ✨ feature

#330 [#321] 최근 검색어 기능 구현
  src/apis/book/index.ts
  src/queries/book/useRecentSearchesQuery.ts
  src/types/book.ts
  src/ui/BookSearch/RecentSearches.tsx
  src/ui/BookSearch/index.tsx
Labels: 🐥 프론트, ✨ feature

#333 [#332] 도서 검색 페이지 > 최근 검색어 UI 수정
  public/icons/search.svg
  src/pages/book/search/index.tsx
  src/queries/book/useRecentSearchesQuery.ts
  src/styles/theme.tsx
  src/ui/BookSearch/RecentSearches.tsx
  src/ui/BookSearch/index.tsx
Labels: 🐥 프론트, ✨ feature

#334 좋아요 마크업에 버튼이 중복되는 부분 수정
  src/ui/common/LikeButton/index.tsx
Labels: 🐥 프론트, 🐛 fix

#338 [#308] 모바일 환경에서 BottomSheet가 부드럽게 닫히지 않는 문제 해결
  src/hooks/useToggle.ts
  src/ui/Group/AddGroupForm.tsx
  src/ui/LoginBottomSheet/index.tsx
  src/ui/common/BottomSheet.tsx
  src/ui/common/BottomSheet/index.tsx
Labels: 🐥 프론트, ♻️ refactor
