Repository prgrms-web-devcourse/Team-Gaerval-Dadok-FE, pull requests merged in 2023-11, with the labels that each got.

#402 [#399] Toast 컴포넌트
  .storybook/preview.tsx
  public/icons/check-circle.svg
  src/stories/Base/Toast.stories.tsx
  src/ui/Base/Portal.tsx
  src/ui/Base/Toast/ToastItem.tsx
  src/ui/Base/Toast/ToastProvider.tsx
  src/ui/Base/Toast/types.ts
  src/ui/Base/Toast/useToast.ts
  tailwind.config.js
Labels: 🐥 프론트, 🔥 v.1.0

#424 [#406] [모임 상세] 멤버 목록 컴포넌트
  public/icons/arrow-left.svg
  src/stories/bookgroup/detail/MemberItem.stories.tsx
  src/stories/bookgroup/detail/ShortMemberInfo.stories.tsx
  src/ui/bookgroup/detail/MemberItem.tsx
  src/ui/bookgroup/detail/ShortMemberInfo.tsx
Labels: 🐥 프론트, ✨ feature, 🔥 v.1.0

#420 [#418] Avatar 컴포넌트
  public/icons/avatar.svg
  src/stories/Base/Avatar.stories.tsx
  src/ui/Base/Avatar.tsx
Labels: 🐥 프론트, ✨ feature, 🔥 v.1.0

#419 [#404][독서모임] 모임 검색 컴포넌트
  public/icons/index.ts
  public/icons/plus.svg
  public/icons/search.svg
  src/stories/Base/FloatingButton.stories.tsx
  src/stories/bookgroup/SearchGroup.stories.tsx
  src/ui/Base/FloatingButton.tsx
  src/ui/Base/bookgroup/SearchGroup.tsx
Labels: 🐥 프론트, ✨ feature, 🔥 v.1.0

#429 [#408] [모임 상세] 게시글 컴포넌트
  src/stories/bookgroup/detail/CommentList.stories.tsx
  src/ui/bookgroup/detail/CommentList.tsx
Labels: 🐥 프론트, ✨ feature, 🔥 v.1.0

#428 [#411][독서 모임] Detail 독서 모임 컴포넌트
  public/icons/calendar.svg
  public/icons/comments.svg
  public/icons/members.svg
  src/stories/bookGroup/DetailBookGroupCard.stories.tsx
  src/v1/bookgroup/DetailBookGroupCard.tsx
  tailwind.config.js
  yarn.lock
Labels: 🐥 프론트, ✨ feature, 🔥 v.1.0

#425 [#410] [북카이브] 북카이브 페이지 (비회원)
  public/icons/arrow-right.svg
  src/stories/Base/Bookshelf/Bookshelf.stories.tsx
  src/ui/BookArchive/BookArchiveForUnAuth.tsx
  src/ui/Bookshelf/Book.tsx
  src/ui/Bookshelf/index.tsx
  src/ui/InteractiveBook/index.tsx
Labels: 🐥 프론트, ✨ feature, 🔥 v.1.0

#423 [#403] [모임 상세] 모임 정보 컴포넌트
  src/constants/dataUrl.ts
  src/stories/bookgroup/BookGroupStatus.stories.tsx
  src/stories/bookgroup/detail/BookGroupInfo.stories.tsx
  src/types/dday.ts
  src/ui/BookArchive/BookArchiveForUnAuth.tsx
  src/ui/book/BookCover.tsx
  src/ui/bookgroup/BookGroupStatus.tsx
  src/ui/bookgroup/detail/BookGroupInfo.tsx
  src/utils/date.ts
  tailwind.config.js
Labels: 🐥 프론트, ✨ feature, 🔥 v.1.0

#438 [#437] [독서모임] Avartar, bookGroupStatus 적용 및 typo 수정
  src/v1/bookGroup/DetailBookGroupCard.tsx
Labels: 🐥 프론트, 🐛 fix, 🔥 v.1.0

#440 [#439] [독서모임] 모임 목록 페이지 리팩토링
  next.config.js
  src/app/group/page.tsx
  src/stories/bookGroup/DetailBookGroupCard.stories.tsx
  src/stories/bookGroup/SearchGroup.stories.tsx
  src/stories/bookGroup/SimpleBookGroupCard.stories.tsx
  src/types/group.ts
  src/ui/Base/FloatingButton.tsx
  src/v1/book/BookCover.tsx
  src/v1/bookGroup/DetailBookGroupCard.tsx
  src/v1/bookGroup/SearchGroup.tsx
  src/v1/bookGroup/SimpleBookGroupCard.tsx
Labels: 🐥 프론트, ♻️ refactor, 🔥 v.1.0

#448 [fix] group 페이지 타입 에러 수정
  src/app/group/page.tsx
Labels: 🐥 프론트, 🐛 fix, 🔥 v.1.0

#427 [#415] [프로필] 프로필 생성 페이지
  src/app/profile/me/add/page.tsx
  src/queries/job/key.ts
  src/queries/job/useAllJobQuery/index.ts
  src/v1/profile/AddJobProfile.tsx
Labels: 🐥 프론트, ✨ feature, 🔥 v.1.0
