Repository prgrms-web-devcourse/Team-Gaerval-Dadok-FE, pull requests merged in 2023-07, with the labels that each got.

#354 [#351] @next/font 를 next/font로 교체
  package.json
  src/styles/font/index.tsx
  yarn.lock
Labels: 🐥 프론트, ♻️ refactor

#356 [#355] DrawerProps 리팩터링
  src/ui/common/BottomSheet.tsx
Labels: 🐥 프론트, ♻️ refactor

#373 [#372] Theme, GlobalStyle, Font 세팅
  src/app/layout.tsx
  src/components/ContextProvider.tsx
  src/styles/font/index.ts
  src/styles/global.css
  src/styles/theme.tsx
  tailwind.config.js
Labels: 🐥 프론트, 🔥 v.1.0

#377 [#376] Storybook 설정 및 GlobalTheme, Font 수정
  src/app/layout.tsx
  src/stories/Button.tsx
  src/stories/Switch.tsx
  src/styles/global.css
  src/styles/theme.tsx
  tailwind.config.js
Labels: 🐥 프론트, 🔥 v.1.0

#380 [#360] Input 컴포넌트 작성
  src/stories/Base/Input.stories.tsx
  src/stories/Button.tsx
  src/styles/global.css
  src/ui/Base/Input.tsx
Labels: 🐥 프론트, ✨ feature, 🔥 v.1.0

#378 [#358] TopNavigation 컴포넌트
  .storybook/main.ts
  public/icons/index.ts
  public/icons/left-arrow.svg
  public/icons/options.svg
  public/icons/post.svg
  public/icons/share.svg
  src/stories/Base/TopNavigation.stories.tsx
  src/ui/Base/TopNavigation.tsx
Labels: 🐥 프론트, 🔥 v.1.0

#379 [#357] TopHeader UI 컴포넌트 및 스토리북 작성
  .prettierrc.json
  public/icons/index.ts
  public/icons/more.svg
  src/stories/Base/TopHeader.stories.tsx
  src/ui/Base/TopHeader.tsx
Labels: 🐥 프론트, ✨ feature, 🔥 v.1.0

#385 [#383] Select 컴포넌트
  .storybook/main.ts
  public/icons/select-icon.svg
  src/stories/Base/Select.stories.tsx
  src/ui/Base/Select.tsx
Labels: 🐥 프론트, 🔥 v.1.0

#386 [#367] Switch 컴포넌트
  src/stories/Base/Switch.stories.tsx
  src/stories/Switch.stories.ts
  src/stories/Switch.tsx
  src/ui/Base/Switch.tsx
Labels: 🐥 프론트, 🔥 v.1.0
