Repository prgrms-web-devcourse/Team-Gaerval-Dadok-FE, pull requests merged in 2023-02, with the labels that each got.

#6 [#5] issue 템플릿 frontmatter 오타 수정
  .github/ISSUE_TEMPLATE/issue-template.md
Labels: 🐥 프론트, 🐛 fix

#9 [#8] 초기 폴더구조 작성
  package.json
  public/icons/.gitKeep
  public/images/.gitKeep
  src/api/.gitKeep
  src/styles/.gitKeep
  src/types/.gitKeep
  src/ui/.gitKeep
  src/utils/.gitKeep
Labels: 🐥 프론트, ⚙️ setting

#11 [#7] CI/CD 설정
  .github/workflows/deploy.yaml
  .github/workflows/lint.yaml
Labels: 🐥 프론트, ⚙️ setting

#15 [#12] 글로벌 스타일 및 폰트 추가
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.module.css
  src/app/page.tsx
  src/components/ChakraThemeProvider.tsx
  src/styles/font/LINESeedKR.woff2
  src/styles/font/index.tsx
  src/styles/theme.tsx
Labels: 🐥 프론트, ⚙️ setting

#20 [#18] axios instance 생성
  package.json
  src/api/.gitKeep
  src/api/axios.ts
  yarn.lock
Labels: 🐥 프론트, ✨ feature

#24 [#23] deploy workflow 제거
  .github/workflows/deploy.yaml
Labels: 🐥 프론트, 📦 chore

#25 [#21] 글로벌 스타일 추가 적용
  public/favicon.ico
  public/next.svg
  public/thirteen.svg
  public/vercel.svg
  src/app/layout.tsx
  src/styles/.gitKeep
  src/styles/font/LINESeedKR-Bd.woff2
  src/styles/font/LINESeedKR-Rg.woff2
  src/styles/font/LINESeedKR-Th.woff2
  src/styles/font/index.tsx
  src/styles/theme.tsx
Labels: 🐥 프론트, ✨ feature

#27 [#17] 하단 네비게이션 바 컴포넌트 작성
  next.config.js
  package.json
  public/icons/.gitKeep
  public/icons/book.svg
  public/icons/bookshelf.svg
  public/icons/hashtag.svg
  public/icons/user.svg
  src/app/layout.tsx
  src/ui/.gitKeep
  src/ui/BottomNavigation/NavigationItem/index.tsx
  src/ui/BottomNavigation/index.tsx
  yarn.lock
Labels: 🐥 프론트, ✨ feature

#33 [#22] BottomSheet 컴포넌트 구현
  src/ui/common/BottomSheet/index.tsx
Labels: 🐥 프론트, ✨ feature

#30 [#28] 마이페이지 마크업
  package.json
  public/icons/close.svg
  src/app/mypage/edit/page.tsx
  src/app/mypage/page.tsx
  src/constants/FormRule/index.ts
  src/styles/theme.tsx
  src/ui/LinkAvatar/index.tsx
  src/ui/UserForm/UserInput/index.tsx
  src/ui/UserForm/index.tsx
  tsconfig.json
  yarn.lock
Labels: 🐥 프론트, ✨ feature

#26 [#14] 모임 목록 페이지 및 모임 상세 페이지 마크업
  package-lock.json
  package.json
  public/icons/commentIcon.svg
  public/icons/goBackIcon.svg
  public/icons/peopleIcon.svg
  src/app/meeting/[id]/page.tsx
  src/app/meeting/page.tsx
  src/app/page.tsx
  src/ui/meeting/MeetingList.tsx
  src/ui/meeting/MeetingListHeader.tsx
  src/ui/meeting/index.tsx
  src/ui/meetingDetail/CommentInputBox.tsx
  src/ui/meetingDetail/CommentsList.tsx
  src/ui/meetingDetail/MeetingDetail.tsx
  src/ui/meetingDetail/ParticipationBtn.tsx
  src/ui/meetingDetail/index.tsx
  yarn.lock
Labels: 🐥 프론트, ✨ feature

#31 [#16] 책 컴포넌트 마크업
  package.json
  public/images/.gitKeep
  public/images/img_chatgptBook.png
  public/images/img_functionalBook.png
  public/images/img_jsDeepDiveBook.png
  public/images/img_refactoringBook.png
  public/images/index.tsx
  src/ui/InteractiveBook/index.tsx
  yarn.lock
Labels: 🐥 프론트, ✨ feature, ⚙️ setting

#39 [#35] BottomNavigation 사이즈 수정
  next.config.js
  public/icons/user.svg
  src/app/bookarchive/page.tsx
  src/ui/BottomNavigation/NavigationItem/index.tsx
  src/ui/BottomNavigation/index.tsx
Labels: 🐥 프론트, 🐛 fix

#41 [#36] UserInput 에서 resetField 작동하지 않는 이슈 해결
  src/constants/FormRule/index.ts
  src/ui/UserForm/UserInput/index.tsx
  src/ui/UserForm/index.tsx
Labels: 🐥 프론트, 🐛 fix

#48 [#46] Issue, Pull Request 템플릿 수정
  .github/ISSUE_TEMPLATE/bug-template.md
  .github/ISSUE_TEMPLATE/discussion-template.md
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/pull_request_template.md
Labels: 🐥 프론트, 🐛 fix

#50 [#46] Issue, Pull Request 템플릿 수정 > Issue Template label 오류 수정
  .github/ISSUE_TEMPLATE/issue-template.md
Labels: 🐥 프론트, 🐛 fix
