Repository prgrms-web-devcourse/Team-Gaerval-Dadok-FE, pull requests merged in 2024-06, with the labels that each got.

#604 [#603] [내 프로필] ErrorBoundary 제거
  src/app/profile/me/page.tsx
  src/queries/bookshelf/useMySummaryBookShelfQuery.ts
  src/v1/profile/bookShelf/MyProfileBookshelfContainer.tsx
  src/v1/profile/bookShelf/ProfileBookShelf.tsx
  src/v1/profile/bookShelf/UserProfileBookshelfContainer.tsx
  src/v1/profile/group/ProfileGroup.tsx
  src/v1/profile/group/ProfileGroupContainer.tsx
  src/v1/profile/info/ProfileInfo.tsx
Labels: 🐥 프론트, 🐛 fix, 🔥 v.1.0

#607 [#602] [모임 생성] 퍼널 progress bar, stepper 구현
  next.config.js
  public/icons/check-stroke.svg
  public/icons/check.svg
  public/icons/index.ts
  src/hocs/withScrollLockOnFocus.tsx
  src/hooks/useRemoveVerticalScroll.ts
  src/stories/base/ProgressBar.stories.tsx
  src/stories/base/Stepper.stories.tsx
  src/v1/base/ProgressBar.tsx
  src/v1/base/Stepper.tsx
  src/v1/bookGroup/create/CreateBookGroupFunnel.tsx
  src/v1/bookGroup/create/steps/EnterTitleStep/EnterTitleStep.tsx
  src/v1/bookGroup/create/steps/SelectJoinTypeStep/fields/JoinPasswordFieldset.tsx
  src/v1/bookGroup/create/steps/SetUpDetailStep/SetUpDetailStep.tsx
  tailwind.config.js
Labels: 🐥 프론트, ✨ feature, 🔥 v.1.0

#606 [#605] Google LightHouse CI 추가
  .github/actions/get-score-comments/action.js
  .github/actions/get-score-comments/action.yml
  .github/workflows/lighthouse.yml
  lighthouserc.js
  package.json
  yarn.lock
Labels: 🐥 프론트, ⚙️ setting, 🔥 v.1.0

#613 [#612] 북카이브 페이지에서 발생하는 무한 리랜더링 버그 수정
  src/app/bookarchive/page.tsx
Labels: 🐥 프론트, 🐛 fix, 🔥 v.1.0

#611 [#608] 페이지 접근 권한 부여
  src/app/group/[groupId]/edit/page.tsx
  src/app/group/[groupId]/join/page.tsx
  src/app/group/create/page.tsx
  src/app/profile/me/add/page.tsx
  src/app/profile/me/edit/page.tsx
  src/app/profile/me/group/page.tsx
  src/hocs/withAuthRequired.tsx
  src/v1/profile/group/ProfileGroupContainer.tsx
Labels: 🐥 프론트, ✨ feature, 🔥 v.1.0

#614 [#610] 로그인 페이지 구현
  public/images/login-landing.jpg
  src/app/global-error.tsx
  src/app/group/[groupId]/not-found.tsx
  src/app/login/page.tsx
  src/app/not-found.tsx
  src/styles/global.css
  src/v1/base/Button.tsx
  src/v1/base/TopHeader.tsx
  src/v1/bookSearch/BestSellers.tsx
  tailwind.config.js
Labels: 🐥 프론트, ✨ feature, 🔥 v.1.0

#615 [#556] 버튼 컴포넌트 disabled style 작성
  src/stories/base/Button.stories.tsx
  src/v1/base/Button.tsx
  src/v1/bookGroup/create/steps/EnterTitleStep/EnterTitleStep.tsx
  src/v1/bookGroup/create/steps/SelectJoinTypeStep/SelectJoinTypeStep.tsx
  src/v1/bookGroup/create/steps/SetUpDetailStep/SetUpDetailStep.tsx
Labels: 🐥 프론트, ✨ feature, 🔥 v.1.0

#617 [#349] 메타 데이터 추가
  src/app/book/sitemap.ts
  src/app/bookshelf/sitemap.ts
  src/app/group/sitemap.ts
  src/app/layout.tsx
  src/app/opengraph-image.jpg
  src/app/robots.ts
  src/app/sitemap.ts
Labels: 🐥 프론트, ✨ feature, 🔥 v.1.0

#620 [#616] 책장 좋아요 뱃지 UI 수정
  next.config.js
  public/icons/heart.svg
  src/v1/base/Badge.tsx
  src/v1/base/LikeButton.tsx
  src/v1/bookGroup/DetailBookGroupCard.tsx
  src/v1/bookShelf/BookShelf.tsx
  src/v1/profile/bookShelf/ProfileBookshelfPresenter.tsx
  src/v1/profile/group/ProfileGroupPresenter.tsx
Labels: 🐥 프론트, ♻️ refactor, 🔥 v.1.0

#621 [#619] PWA 구현
  .gitignore
  public/images/icon-128x128.png
  public/images/icon-192x192.png
  public/images/icon-256x256.png
  public/images/icon-384x384.png
  public/images/icon-512x512.png
  public/images/splash-screens/10.2__iPad_landscape.png
  public/images/splash-screens/10.2__iPad_portrait.png
  public/images/splash-screens/10.5__iPad_Air_landscape.png
  public/images/splash-screens/10.5__iPad_Air_portrait.png
  public/images/splash-screens/10.9__iPad_Air_landscape.png
  public/images/splash-screens/10.9__iPad_Air_portrait.png
  public/images/splash-screens/11__iPad_Pro_M4_landscape.png
  public/images/splash-screens/11__iPad_Pro_M4_portrait.png
  public/images/splash-screens/11__iPad_Pro__10.5__iPad_Pro_landscape.png
  public/images/splash-screens/11__iPad_Pro__10.5__iPad_Pro_portrait.png
  public/images/splash-screens/12.9__iPad_Pro_landscape.png
  public/images/splash-screens/12.9__iPad_Pro_portrait.png
  public/images/splash-screens/13__iPad_Pro_M4_landscape.png
  public/images/splash-screens/13__iPad_Pro_M4_portrait.png
  public/images/splash-screens/4__iPhone_SE__iPod_touch_5th_generation_and_later_landscape.png
  public/images/splash-screens/4__iPhone_SE__iPod_touch_5th_generation_and_later_portrait.png
  public/images/splash-screens/8.3__iPad_Mini_landscape.png
  public/images/splash-screens/8.3__iPad_Mini_portrait.png
  public/images/splash-screens/9.7__iPad_Pro__7.9__iPad_mini__9.7__iPad_Air__9.7__iPad_landscape.png
  public/images/splash-screens/9.7__iPad_Pro__7.9__iPad_mini__9.7__iPad_Air__9.7__iPad_portrait.png
  public/images/splash-screens/iPhone_11_Pro_Max__iPhone_XS_Max_landscape.png
  public/images/splash-screens/iPhone_11_Pro_Max__iPhone_XS_Max_portrait.png
  public/images/splash-screens/iPhone_11__iPhone_XR_landscape.png
  public/images/splash-screens/iPhone_11__iPhone_XR_portrait.png
  public/images/splash-screens/iPhone_13_mini__iPhone_12_mini__iPhone_11_Pro__iPhone_XS__iPhone_X_landscape.png
  public/images/splash-screens/iPhone_13_mini__iPhone_12_mini__iPhone_11_Pro__iPhone_XS__iPhone_X_portrait.png
  public/images/splash-screens/iPhone_14_Plus__iPhone_13_Pro_Max__iPhone_12_Pro_Max_landscape.png
  public/images/splash-screens/iPhone_14_Plus__iPhone_13_Pro_Max__iPhone_12_Pro_Max_portrait.png
  public/images/splash-screens/iPhone_14__iPhone_13_Pro__iPhone_13__iPhone_12_Pro__iPhone_12_landscape.png
  public/images/splash-screens/iPhone_14__iPhone_13_Pro__iPhone_13__iPhone_12_Pro__iPhone_12_portrait.png
  public/images/splash-screens/iPhone_15_Pro_Max__iPhone_15_Plus__iPhone_14_Pro_Max_landscape.png
  public/images/splash-screens/iPhone_15_Pro_Max__iPhone_15_Plus__iPhone_14_Pro_Max_portrait.png
  public/images/splash-screens/iPhone_15_Pro__iPhone_15__iPhone_14_Pro_landscape.png
  public/images/splash-screens/iPhone_15_Pro__iPhone_15__iPhone_14_Pro_portrait.png
  public/images/splash-screens/iPhone_8_Plus__iPhone_7_Plus__iPhone_6s_Plus__iPhone_6_Plus_landscape.png
  public/images/splash-screens/iPhone_8_Plus__iPhone_7_Plus__iPhone_6s_Plus__iPhone_6_Plus_portrait.png
  public/images/splash-screens/iPhone_8__iPhone_7__iPhone_6s__iPhone_6__4.7__iPhone_SE_landscape.png
  public/images/splash-screens/iPhone_8__iPhone_7__iPhone_6s__iPhone_6__4.7__iPhone_SE_portrait.png
  public/pwaServiceWorker.js
  src/app/group/page.tsx
  src/app/layout.tsx
  src/app/manifest.webmanifest
  src/components/ContextProvider.tsx
  src/components/PWAServiceWorkerProvider.tsx
  src/constants/metadata/appleSplashScreens.ts
  src/constants/metadata/index.ts
  src/v1/base/BottomNavigation.tsx
  src/v1/base/Toast/ToastProvider.tsx
  src/v1/layout/Layout.tsx
Labels: 🐥 프론트, ✨ feature, 🔥 v.1.0

#624 [#623] [도서 검색] Input 검색 아이콘 Layout Shift 해결
  src/v1/base/Input.tsx
Labels: 🐥 프론트, ♻️ refactor, 🔥 v.1.0

#628 [#625] Toast 컴포넌트 icon이 잘리는 문제 해결
  public/icons/check-circle.svg
  public/icons/error-circle.svg
  public/icons/warning-circle.svg
Labels: 🐥 프론트, ♻️ refactor, 🔥 v.1.0

#626 [#622] BottomActionButton 패딩 수정
  src/app/book/[bookId]/page.tsx
  src/app/group/[groupId]/page.tsx
  src/styles/global.css
  src/v1/base/BottomActionButton.tsx
  src/v1/bookGroup/create/steps/SelectJoinTypeStep/SelectJoinTypeStep.tsx
  src/v1/bookGroup/create/steps/SetUpDetailStep/SetUpDetailStep.tsx
  src/v1/layout/Layout.tsx
Labels: 🐥 프론트, 🐛 fix, 🔥 v.1.0

#630 [#629] tailwind config color 정리
  src/app/bookshelf/[bookshelfId]/page.tsx
  src/v1/base/BottomNavigation.tsx
  src/v1/base/Button.tsx
  src/v1/base/Switch.tsx
  src/v1/bookGroup/BookInfoCard.tsx
  src/v1/bookGroup/SimpleBookGroupCard.tsx
  src/v1/bookGroup/create/steps/SelectJoinTypeStep/fields/JoinTypeRadioCard.tsx
  src/v1/bookSearch/BestSellers.tsx
  src/v1/bookShelf/BookShelf.tsx
  tailwind.config.js
Labels: 🐥 프론트, ♻️ refactor, 🔥 v.1.0

#631 [#627] 불필요한 utils, hooks, constants 정리 및 import문 통일
  src/apis/user.tsx
  src/app/bookshelf/[bookshelfId]/page.tsx
  src/app/login/page.tsx
  src/app/profile/me/page.tsx
  src/constants/FormRule/index.ts
  src/constants/groupRadioValues.ts
  src/constants/index.ts
  src/constants/initialBookGroupComments.ts
  src/hooks/auth/atoms/index.ts
  src/hooks/auth/index.ts
  src/hooks/auth/useAuth.ts
  src/hooks/toast/atoms/index.ts
  src/hooks/toast/index.ts
  src/hooks/toast/useToast.ts
  src/hooks/useScroll.ts
  src/hooks/useToggle.ts
  src/ui/AuthRequired/index.tsx
  src/ui/BookDetail/BookComment.tsx
  src/ui/BookDetail/BookCommentList.tsx
  src/ui/BookDetail/index.tsx
  src/ui/FormInput/index.tsx
  src/ui/FormSelect/index.tsx
  src/ui/Group/EditGroupForm.tsx
  src/ui/Group/GroupComment/index.tsx
  src/ui/Group/GroupDetail/GroupInfo.tsx
  src/ui/Group/GroupDetail/index.tsx
  src/ui/common/Toast/ToastItem.tsx
  src/ui/common/Toast/index.tsx
  src/utils/storage.ts
  src/v1/base/BottomActionButton.tsx
  src/v1/base/Drawer.tsx
  src/v1/base/FloatingButton.tsx
  src/v1/base/LoginBottomActionButton.tsx
  src/v1/base/Menu.tsx
  src/v1/base/ShareButton.tsx
  src/v1/base/TextArea.tsx
  src/v1/base/Toast/ToastItem.tsx
  src/v1/base/Toast/ToastProvider.tsx
  src/v1/base/Toast/useToast.ts
  src/v1/book/BookCover.tsx
  src/v1/bookGroup/DetailBookGroupCard.tsx
  src/v1/bookGroup/create/CreateBookGroupFunnel.tsx
  src/v1/bookGroup/create/steps/EnterTitleStep/EnterTitleStep.tsx
  src/v1/bookGroup/create/steps/SelectJoinTypeStep/SelectJoinTypeStep.tsx
  src/v1/bookGroup/create/steps/SelectJoinTypeStep/fields/JoinTypeFieldset.tsx
  src/v1/bookGroup/detail/ShortMemberInfo.tsx
  src/v1/bookShelf/BookShelfCard.tsx
  src/v1/bookShelf/BookShelfRow.tsx
  src/v1/comment/BookCommentList.tsx
  src/v1/comment/BookGroupCommentList.tsx
  src/v1/comment/CommentList.tsx
  src/v1/profile/bookShelf/MyProfileBookshelfContainer.tsx
  src/v1/profile/bookShelf/ProfileBookShelf.tsx
  src/v1/profile/bookShelf/UserProfileBookshelfContainer.tsx
  src/v1/profile/group/ProfileGroup.tsx
  src/v1/profile/group/ProfileGroupContainer.tsx
  src/v1/profile/info/MyProfileInfoContainer.tsx
  src/v1/profile/info/ProfileInfo.tsx
  src/v1/profile/info/UserProfileInfoContainer.tsx
Labels: 🐥 프론트, 📦 chore, 🔥 v.1.0

#633 [#632] 사용하지 않는 라이브러리 제거
  .storybook/main.ts
  .storybook/preview.tsx
  package.json
  src/app/layout.tsx
  src/components/ChakraThemeProvider.tsx
  src/components/ContextProvider.tsx
  src/styles/global.css
  src/styles/theme.tsx
  src/ui/BookDetail/BookInfo.tsx
  src/ui/BookDetail/CommentDrawer.tsx
  src/ui/BookDetail/index.tsx
  src/ui/BookSearch/RecentSearches.tsx
  src/ui/BookSearch/SearchedBook.tsx
  src/ui/BookSearch/index.tsx
  src/ui/BottomNavigation/NavigationItem/index.tsx
  src/ui/BottomNavigation/index.tsx
  src/ui/FormRadio/index.tsx
  src/ui/Group/GroupComment/CommentDeleteModal.tsx
  src/ui/Group/GroupComment/CommentInputBox.tsx
  src/ui/Group/GroupComment/CommentModifyModal.tsx
  src/ui/Group/GroupComment/GuideMessage.tsx
  src/ui/Group/GroupHeader.tsx
  src/ui/Group/GroupList/GroupListItem.tsx
  src/ui/Group/GroupList/index.tsx
  src/ui/Group/GroupSearch.tsx
  src/ui/InteractiveBook/index.tsx
  src/ui/InteractiveBookShelf/InitialBookShelfData.tsx
  src/ui/InteractiveBookShelf/index.tsx
  src/ui/LoginBottomSheet/CloseButton/index.tsx
  src/ui/LoginBottomSheet/index.tsx
  src/ui/Recommended/RecommendedBooks.tsx
  src/ui/Recommended/RecommendedBookshelf.tsx
  src/ui/Recommended/index.tsx
  src/ui/UserJobInfoTag/index.tsx
  src/ui/common/BookshelfLike/LikeButton.tsx
  src/ui/common/BookshelfLike/LikeCount.tsx
  src/ui/common/BookshelfLike/index.tsx
  src/ui/common/BottomSheet.tsx
  src/ui/common/Button/index.tsx
  src/ui/common/IconButton/index.tsx
  src/ui/common/Logo/index.tsx
  src/ui/common/Menu/Menu.tsx
  src/ui/common/Menu/MenuItem.tsx
  src/ui/common/Menu/index.ts
  src/ui/common/TopNavigation/index.tsx
  yarn.lock
Labels: 🐥 프론트, ♻️ refactor, 🔥 v.1.0

#645 [#640] 로그인하지 않은 사용자의 진입점을 로그인 페이지로 수정
  next.config.js
  src/app/login/page.tsx
  src/middleware.ts
Labels: 🐥 프론트, ✨ feature, 🔥 v.1.0

#647 [#646] /scripts 파일을 esm으로 변경
  package.json
  scripts/server.mjs
  scripts/updateDevHost.mjs
Labels: 🐥 프론트, 📦 chore, 🔥 v.1.0
