Repository prgrms-web-devcourse/Team-Gaerval-Dadok-FE, pull requests merged in 2024-04, with the labels that each got.

#501 [#498] useFunnel 작성
  src/hooks/useFunnel.tsx
  src/utils/assert.ts
  src/v1/base/Funnel/Funnel.tsx
Labels: 🐥 프론트, ✨ feature, 🔥 v.1.0

#500 [#497] [책 상세] 책 상세 페이지 api 연결
  src/apis/book/index.ts
  src/app/book/[bookId]/page.tsx
  src/app/group/[groupId]/page.tsx
  src/components/ReactQueryProvider.tsx
  src/queries/book/useBookCommentPatchMutation.ts
  src/queries/book/useBookCommentsQuery.ts
  src/queries/book/useBookmarkUserQuery.ts
  src/queries/book/useCreateBookCommentMutation.ts
  src/queries/book/useDeleteBookCommentMutation.ts
  src/queries/book/usePatchBookCommentMutation.ts
  src/queries/book/useUpdateBookmarkMutation.ts
  src/types/book.ts
  src/ui/BookDetail/BookCommentList.tsx
  src/v1/base/LoginBottomActionButton.tsx
  src/v1/book/detail/BookInfo.tsx
  src/v1/comment/BookCommentList.tsx
  src/v1/comment/CommentDrawer.tsx
  src/v1/comment/CommentList.tsx
Labels: 🐥 프론트, ✨ feature, 🔥 v.1.0

#511 [#506] 로컬 환경에서 Host 수정
  package.json
  updateDevHost.js
Labels: 🐥 프론트, ✨ feature, ⚙️ setting, 🔥 v.1.0

#508 [#507] [프로필] 로그아웃 햄버거 구현
  src/app/profile/me/page.tsx
Labels: 🐥 프론트, ✨ feature, 🔥 v.1.0

#513 [#512] [모임 상세] 모임 게시글 수정/삭제 기능 구현
  src/queries/group/useDeleteBookGroupCommentMutation.ts
  src/queries/group/usePatchBookGroupCommentMutation.ts
  src/v1/comment/BookGroupCommentList.tsx
Labels: 🐥 프론트, ✨ feature, 🔥 v.1.0

#510 [#509] [레이아웃] BottomNavigation 버그 및 UI 수정
  src/app/layout.tsx
  src/components/ContextProvider.tsx
  src/styles/global.css
  src/v1/base/BottomNavigation.tsx
  src/v1/layout/Layout.tsx
  tailwind.config.js
Labels: 🐥 프론트, 🐛 fix, 🔥 v.1.0

#517 [#504] [모임 상세] 모임 게시글 작성 기능 구현
  src/queries/group/useCreateBookGroupCommentMutation.ts
  src/v1/bookGroup/BookGroupNavigation.tsx
Labels: 🐥 프론트, ✨ feature, 🔥 v.1.0

#520 [#516] DatePicker 컴포넌트
  public/icons/index.ts
  public/icons/select-icon.svg
  src/stories/base/DatePicker.stories.tsx
  src/styles/global.css
  src/utils/date.ts
  src/v1/base/DatePicker.tsx
Labels: 🐥 프론트, ✨ feature, 🔥 v.1.0

#519 [#518] Input 컴포넌트 style 추가
  src/stories/base/Input.stories.tsx
  src/v1/base/Input.tsx
Labels: 🐥 프론트, ✨ feature, 🔥 v.1.0

#522 [#521] TextArea 컴포넌트
  src/stories/base/TextArea.stories.tsx
  src/v1/base/ErrorMessage.tsx
  src/v1/base/InputLength.tsx
  src/v1/base/TextArea.tsx
Labels: 🐥 프론트, ✨ feature, 🔥 v.1.0

#525 [#524] Menu 컴포넌트 개선
  src/hooks/useOutsideClickRef.ts
  src/v1/base/Menu.tsx
Labels: 🐥 프론트, 🐛 fix, 🔥 v.1.0

#528 [#526] 도서 검색 페이지 개선
  src/app/book/search/page.tsx
  src/app/bookarchive/page.tsx
  src/queries/book/useBookSearchQuery.ts
  src/queries/book/useRecentSearchesQuery.ts
  src/stories/bookSearch/RecentSearch.stories.tsx
  src/stories/bookSearch/SearchResult.stories.tsx
  src/styles/global.css
  src/v1/book/BookCover.tsx
  src/v1/bookSearch/BookSearchList.tsx
  src/v1/bookSearch/RecentSearchList.tsx
  src/v1/bookSearch/SearchResult.tsx
  src/v1/layout/Layout.tsx
Labels: 🐥 프론트, ♻️ refactor, 🔥 v.1.0

#527 [#523] [모임 상세] 모임 수정 페이지
  src/app/group/[groupId]/edit/page.tsx
  src/queries/group/useBookGroupQuery.ts
  src/styles/theme.tsx
  src/types/group.ts
  src/v1/base/DatePicker.tsx
  src/v1/base/InputLength.tsx
  src/v1/base/TextArea.tsx
  src/v1/bookGroup/edit/BookGroupEditDateForm.tsx
  src/v1/bookGroup/edit/BookGroupEditIntroduceForm.tsx
  src/v1/bookGroup/edit/BookGroupEditTitleForm.tsx
  src/v1/bookGroup/edit/BookGroupEditTopNavigation.tsx
Labels: 🐥 프론트, ✨ feature, 🔥 v.1.0

#532 [#529] redirect 페이지 개선, 토큰 업데이트 로직 개선
  src/apis/core/axios.ts
  src/app/login/redirect/page.tsx
Labels: 🐥 프론트, 🐛 fix, 🔥 v.1.0

#536 [#530] FloatingButton 컴포넌트 적용
  public/icons/book-plus.svg
  public/icons/plus.svg
  src/app/group/page.tsx
  src/v1/base/FloatingButton.tsx
  src/v1/bookGroup/SearchGroup.tsx
  tailwind.config.js
Labels: 🐥 프론트, ✨ feature, 🔥 v.1.0

#537 [#505] [모임 상세] 모임 삭제 기능 구현
  src/app/group/[groupId]/not-found.tsx
  src/app/group/[groupId]/page.tsx
  src/components/ReactQueryProvider.tsx
  src/queries/group/useDeleteBookGroupMutation.ts
  src/v1/base/Button.tsx
  src/v1/base/Toast/ToastProvider.tsx
  src/v1/bookGroup/BookGroupNavigation.tsx
Labels: 🐥 프론트, ✨ feature, 🔥 v.1.0

#539 [#535] [독서모임] 독서모임 목록 페이지 개선
  src/app/group/page.tsx
  src/app/profile/me/group/page.tsx
  src/v1/base/TopHeader.tsx
  src/v1/bookGroup/DetailBookGroupCard.tsx
  src/v1/bookGroup/SearchGroup.tsx
  src/v1/bookGroup/SimpleBookGroupCard.tsx
  tailwind.config.js
Labels: 🐥 프론트, 🐛 fix, 🔥 v.1.0

#545 [#544] vscode react component snippet 작성
  .vscode/react.code-snippets
Labels: 🐥 프론트, ✨ feature

#542 [#540] [모임 생성] 모임 상세 퍼널 마크업
  src/stories/bookGroup/create/funnel/SetUpDetailStep.stories.tsx
  src/v1/base/InputLength.tsx
  src/v1/bookGroup/BookInfoCard.tsx
  src/v1/bookGroup/create/funnel/SetUpDetailStep.tsx
  src/v1/bookGroup/create/funnel/index.ts
Labels: 🐥 프론트, ✨ feature, 🔥 v.1.0

#541 [#531] 로컬 서버에 https 적용
  package.json
  scripts/init-mkcert.sh
  scripts/server.js
  scripts/updateDevHost.js
Labels: 🐥 프론트, ✨ feature, ⚙️ setting, 🔥 v.1.0

#551 [#548] [레이아웃] 모바일 환경에서의 스크롤 버그 수정
  src/v1/layout/Layout.tsx
Labels: 🐥 프론트, 🐛 fix, 🔥 v.1.0

#550 [#549] 'unable to verify first certificate' 에러 해결
  package.json
  scripts/server.js
Labels: 🐥 프론트, 🐛 fix, ⚙️ setting, 🔥 v.1.0

#555 [#554] 스토리북 preview decorator에서 Layout 제거
  .storybook/preview.tsx
  src/stories/meta.tsx
Labels: 🐥 프론트, ✨ feature, ⚙️ setting, 🔥 v.1.0

#560 [#543] [모임 생성] 책 선택 퍼널
  .storybook/preview.tsx
  public/icons/search.svg
  src/app/book/search/page.tsx
  src/stories/base/Input.stories.tsx
  src/stories/bookGroup/create/funnel/SelectBookStep.stories.tsx
  src/types/book.ts
  src/v1/base/Input.tsx
  src/v1/base/Select.tsx
  src/v1/bookGroup/create/funnel/SelectBookStep.tsx
  src/v1/bookSearch/BookSearchList.tsx
  tailwind.config.js
Labels: 🐥 프론트, ✨ feature, 🔥 v.1.0
