Repository prgrms-web-devcourse/Team-Gaerval-Dadok-FE, pull requests merged in 2024-05, with the labels that each got.

#565 [#562] [모임 생성] 모임 이름 퍼널
  src/stories/bookGroup/create/funnel/EnterTitleStep.stories.tsx
  src/v1/bookGroup/create/steps/EnterTitleStep/EnterTitleStep.tsx
  src/v1/bookGroup/create/steps/EnterTitleStep/fields/TitleField.tsx
  src/v1/bookGroup/create/steps/EnterTitleStep/fields/index.ts
  src/v1/bookGroup/create/steps/EnterTitleStep/index.ts
Labels: 🐥 프론트, ✨ feature, 🔥 v.1.0

#566 [#564] BottomActionButton 컴포넌트 position 속성 수정
  src/v1/base/BottomActionButton.tsx
Labels: 🐥 프론트, 🐛 fix, 🔥 v.1.0

#568 [#563] [모임 생성] 모임 가입문제 퍼널
  src/stories/bookGroup/create/steps/SelectJoinTypeStep.stories.tsx
  src/v1/bookGroup/create/steps/SelectJoinTypeStep/SelectJoinTypeStep.tsx
  src/v1/bookGroup/create/steps/SelectJoinTypeStep/fields/JoinPasswordFieldset.tsx
  src/v1/bookGroup/create/steps/SelectJoinTypeStep/fields/JoinTypeFieldset.tsx
  src/v1/bookGroup/create/steps/SelectJoinTypeStep/fields/JoinTypeRadioCard.tsx
  src/v1/bookGroup/create/steps/SelectJoinTypeStep/fields/index.ts
  src/v1/bookGroup/create/steps/SelectJoinTypeStep/index.ts
  tailwind.config.js
Labels: 🐥 프론트, ✨ feature, 🔥 v.1.0

#569 [#552] next custom server 구동 시 hmr이 동작하지 않는 문제 해결
  package.json
  patches/next+13.4.7.dev.patch
  yarn.lock
Labels: 🐥 프론트, 🐛 fix, 🔥 v.1.0

#567 [#561] [모임 생성] 모임 상세 퍼널 개선
  src/stories/bookGroup/create/funnel/SetUpDetailStep.stories.tsx
  src/stories/bookGroup/create/steps/SetUpDetailStep.stories.tsx
  src/styles/global.css
  src/v1/bookGroup/create/funnel/index.ts
  src/v1/bookGroup/create/steps/SetUpDetailStep/SetUpDetailStep.tsx
  src/v1/bookGroup/create/steps/SetUpDetailStep/index.ts
Labels: 🐥 프론트, ♻️ refactor, 🔥 v.1.0

#573 [#571] Drawer 컴포넌트 style 개선
  src/hooks/useBodyScrollLock.ts
  src/v1/base/Drawer.tsx
  src/v1/base/Portal.tsx
  src/v1/comment/CommentDrawer.tsx
Labels: 🐥 프론트, 🐛 fix, 🔥 v.1.0

#572 [#559] BookInfoCard 컴포넌트 수정 및 goToBookSelectStep 이벤트 추가
  src/stories/bookGroup/create/steps/SetUpDetailStep.stories.tsx
  src/v1/bookGroup/BookInfoCard.tsx
  src/v1/bookGroup/create/funnel/SelectBookStep.tsx
  src/v1/bookGroup/create/steps/SetUpDetailStep/SetUpDetailStep.tsx
Labels: 🐥 프론트, ✨ feature, 🔥 v.1.0

#577 [#574] FloatingButton 버그 수정
  src/app/group/page.tsx
  src/v1/base/FloatingButton.tsx
  tailwind.config.js
Labels: 🐥 프론트, 🐛 fix, 🔥 v.1.0

#579 [#578] iOS 환경에서의 DatePicker UI 수정
  src/styles/global.css
Labels: 🐥 프론트, 🐛 fix, 🔥 v.1.0

#584 [#583] Switch 컴포넌트 style 수정
  src/v1/base/Switch.tsx
Labels: 🐥 프론트, 🐛 fix, 🔥 v.1.0

#582 [#581] [모임 생성] 모임 생성 퍼널 페이지 작성
  src/apis/group/index.ts
  src/app/group/create/page.tsx
  src/hooks/useFunnel.tsx
  src/queries/group/useCreateBookGroupMutation.ts
  src/stories/bookGroup/create/steps/EnterTitleStep.stories.tsx
  src/stories/bookGroup/create/steps/SelectBookStep.stories.tsx
  src/stories/bookGroup/create/steps/SelectJoinTypeStep.stories.tsx
  src/stories/bookGroup/create/steps/SetUpDetailStep.stories.tsx
  src/ui/Group/AddGroupForm.tsx
  src/v1/base/Funnel.tsx
  src/v1/bookGroup/create/CreateBookGroupFunnel.tsx
  src/v1/bookGroup/create/funnel/index.ts
  src/v1/bookGroup/create/steps/EnterTitleStep/EnterTitleStep.tsx
  src/v1/bookGroup/create/steps/EnterTitleStep/fields/TitleField.tsx
  src/v1/bookGroup/create/steps/EnterTitleStep/index.ts
  src/v1/bookGroup/create/steps/SelectBookStep/SelectBookStep.tsx
  src/v1/bookGroup/create/steps/SelectJoinTypeStep/SelectJoinTypeStep.tsx
  src/v1/bookGroup/create/steps/SelectJoinTypeStep/fields/JoinPasswordFieldset.tsx
  src/v1/bookGroup/create/steps/SelectJoinTypeStep/fields/JoinTypeFieldset.tsx
  src/v1/bookGroup/create/steps/SelectJoinTypeStep/index.ts
  src/v1/bookGroup/create/steps/SetUpDetailStep/SetUpDetailStep.tsx
  src/v1/bookGroup/create/steps/SetUpDetailStep/index.ts
  src/v1/bookGroup/create/steps/index.ts
  src/v1/bookGroup/create/types.ts
Labels: 🐥 프론트, ✨ feature, 🔥 v.1.0

#576 [#575] Drawer 컴포넌트 개선
  src/hooks/useBodyScrollLock.ts
  src/hooks/useRemoveVerticalScroll.ts
  src/styles/global.css
  src/utils/eventListener.ts
  src/v1/base/Drawer.tsx
  src/v1/comment/CommentDrawer.tsx
Labels: 🐥 프론트, ♻️ refactor, 🔥 v.1.0

#586 [#585] [프로필 페이지] '참여한 모임' 영역 사용자가 모임장인 모임에 마크 추가
  src/app/profile/me/group/page.tsx
  src/app/profile/me/page.tsx
  src/v1/profile/bookShelf/ProfileBookshelfPresenter.tsx
  src/v1/profile/group/ProfileGroupContainer.tsx
  src/v1/profile/group/ProfileGroupPresenter.tsx
Labels: 🐥 프론트, 🐛 fix, 🔥 v.1.0

#587 [#557] [도서 검색] 최근 검색어 api 요청
  src/apis/book/index.ts
  src/app/book/search/page.tsx
Labels: 🐥 프론트, ✨ feature, 🔥 v.1.0

#594 [#591] 3D 책 컴포넌트, 책장 페이지 개선
  src/app/bookshelf/[bookshelfId]/page.tsx
  src/queries/bookshelf/useBookShelfInfoQuery.ts
  src/styles/global.css
  src/v1/bookShelf/BookShelf.tsx
  src/v1/bookShelf/BookShelfCard.tsx
  src/v1/bookShelf/BookShelfRow.tsx
Labels: 🐥 프론트, ♻️ refactor, 🔥 v.1.0

#597 [#595] Toast UI 개선
  public/icons/check-circle.svg
  public/icons/error-circle.svg
  public/icons/error-with-exclamation.svg
  public/icons/index.ts
  public/icons/warning-circle.svg
  src/app/bookshelf/[bookshelfId]/page.tsx
  src/app/group/page.tsx
  src/stories/base/Toast.stories.tsx
  src/v1/base/ErrorMessage.tsx
  src/v1/base/ShareButton.tsx
  src/v1/base/Toast/ToastItem.tsx
  src/v1/base/Toast/types.ts
  src/v1/book/detail/BookInfo.tsx
  src/v1/profile/AddJobProfile.tsx
  src/v1/profile/EditProfile.tsx
Labels: 🐥 프론트, ♻️ refactor, 🔥 v.1.0

#593 [#592] [도서 검색] 검색 키워드 및 결과 유지 기능 구현
  public/icons/close.svg
  scripts/server.js
  src/app/book/search/page.tsx
  src/hooks/useQueryParams.ts
  src/styles/global.css
  src/v1/base/Input.tsx
  src/v1/bookSearch/BestSellers.tsx
  src/v1/bookSearch/RecentSearchList.tsx
Labels: 🐥 프론트, ✨ feature, 🔥 v.1.0

#600 [#596] accessToken이 만료된 직후 다른 페이지 접근할 때 에러 페이지를 보여주지 않고 새로고침
  src/apis/core/axios.ts
  src/app/error.tsx
  src/app/global-error.tsx
  src/app/layout.tsx
  src/components/AuthFailedErrorBoundary.tsx
  src/components/ContextProvider.tsx
  src/components/ReactQueryProvider.tsx
  src/types/customError/AuthRefreshIgnoredError.ts
  src/types/customError/index.ts
Labels: 🐥 프론트, 🐛 fix, 🔥 v.1.0
